"""fix_avatar

Revision ID: 204fe28e594f
Revises: d18c5343b334
Create Date: 2025-11-26 13:44:36.333907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '204fe28e594f'
down_revision: Union[str, Sequence[str], None] = 'd18c5343b334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('avatars', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avatars', sa.Column('url', sa.VARCHAR(length=2048), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
