"""add_skills

Revision ID: cb085172f4a8
Revises: d94ac54a929e
Create Date: 2025-11-20 11:34:33.172493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb085172f4a8'
down_revision: Union[str, Sequence[str], None] = 'd94ac54a929e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('current_timestamp(0)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('current_timestamp(0)'), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills')),
    sa.UniqueConstraint('name', name=op.f('uq_skills_name'))
    )
    op.create_index('idx_skill_name_lower', 'skills', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('user_skills_association',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_user_skills_association_skill_id_skills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_skills_association_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'skill_id', name=op.f('pk_user_skills_association'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_skills_association')
    op.drop_index('idx_skill_name_lower', table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
