"""fix_user

Revision ID: e6f0a24c4840
Revises: 204fe28e594f
Create Date: 2025-11-26 17:36:03.633738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6f0a24c4840'
down_revision: Union[str, Sequence[str], None] = '204fe28e594f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_current_avatar_id_avatars'), 'users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_users_current_avatar_id_avatars'), 'users', 'avatars', ['current_avatar_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_current_avatar_id_avatars'), 'users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_users_current_avatar_id_avatars'), 'users', 'avatars', ['current_avatar_id'], ['id'])
    # ### end Alembic commands ###
