"""gin_index_search

Revision ID: 767fce0aaaa3
Revises: 747ef47b6f3b
Create Date: 2025-11-13 18:00:15.369756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '767fce0aaaa3'
down_revision: Union[str, Sequence[str], None] = '747ef47b6f3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'idx_users_fuzzy_search',
        'users',
        [
            sa.text("lower(first_name || ' ' || last_name || ' ' || position || ' ' || email) gin_trgm_ops")
        ],
        unique=False,
        postgresql_using='gin'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_fuzzy_search', table_name='users', postgresql_using='gin')
    # ### end Alembic commands ###

    op.execute("DROP EXTENSION IF EXISTS pg_trgm;")
