"""legal_entities_and_departments

Revision ID: 8f19d7b93e9b
Revises: 447fc7fffa5f
Create Date: 2025-11-11 12:12:13.291226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f19d7b93e9b'
down_revision: Union[str, Sequence[str], None] = '447fc7fffa5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_entities',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('current_timestamp(0)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('current_timestamp(0)'), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legal_entities')),
    sa.UniqueConstraint('name', name=op.f('uq_legal_entities_name'))
    )
    op.create_table('departments',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('legal_entity_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('current_timestamp(0)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('current_timestamp(0)'), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], name=op.f('fk_departments_legal_entity_id_legal_entities')),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], name=op.f('fk_departments_parent_id_departments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('name', name=op.f('uq_departments_name'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('departments')
    op.drop_table('legal_entities')
    # ### end Alembic commands ###
