"""update_user_and_department

Revision ID: 9eb8c9f2699d
Revises: 8f19d7b93e9b
Create Date: 2025-11-11 13:37:43.158442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9eb8c9f2699d'
down_revision: Union[str, Sequence[str], None] = '8f19d7b93e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ACTIVE', 'INACTIVE', 'VACATION', 'SICK', 'REMOTE', 'TRIP', name='employeestatusenum').create(op.get_bind())
    op.add_column('departments', sa.Column('manager_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(op.f('uq_departments_manager_id'), 'departments', ['manager_id'])
    op.create_foreign_key(op.f('fk_departments_manager_id_users'), 'departments', 'users', ['manager_id'], ['id'],
                          ondelete='SET NULL', deferrable=True,
                          initially='DEFERRED',
                          use_alter=True)
    op.alter_column('users', 'employee_status',
                    existing_type=sa.VARCHAR(length=32),
                    type_=postgresql.ENUM('ACTIVE', 'INACTIVE', 'VACATION', 'SICK', 'REMOTE', 'TRIP',
                                          name='employeestatusenum'),
                    existing_nullable=True,
                    postgresql_using='employee_status::employeestatusenum')
    op.create_foreign_key(op.f('fk_users_department_id_departments'), 'users', 'departments', ['department_id'], ['id'])
    op.drop_column('users', 'manager_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('manager_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_users_department_id_departments'), 'users', type_='foreignkey')
    op.alter_column('users', 'employee_status',
                    existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', 'VACATION', 'SICK', 'REMOTE', 'TRIP',
                                                  name='employeestatusenum'),
                    type_=sa.VARCHAR(length=32),
                    existing_nullable=True)
    op.drop_constraint(op.f('fk_departments_manager_id_users'), 'departments', type_='foreignkey')
    op.drop_constraint(op.f('uq_departments_manager_id'), 'departments', type_='unique')
    op.drop_column('departments', 'manager_id')
    sa.Enum('ACTIVE', 'INACTIVE', 'VACATION', 'SICK', 'REMOTE', 'TRIP', name='employeestatusenum').drop(op.get_bind())
    # ### end Alembic commands ###
