"""edit_user_position

Revision ID: b16083302cde
Revises: 9eb8c9f2699d
Create Date: 2025-11-11 16:11:25.056223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b16083302cde'
down_revision: Union[str, Sequence[str], None] = '9eb8c9f2699d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_departments_manager_id_users'), 'departments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_departments_manager_id_users'), 'departments', 'users', ['manager_id'], ['id'], ondelete='SET NULL')
    op.alter_column('users', 'position',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'position',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('fk_departments_manager_id_users'), 'departments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_departments_manager_id_users'), 'departments', 'users', ['manager_id'], ['id'], ondelete='SET NULL', initially='DEFERRED', deferrable=True)
    # ### end Alembic commands ###
