"""avatar_add

Revision ID: d18c5343b334
Revises: cb085172f4a8
Create Date: 2025-11-25 17:15:00.682803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd18c5343b334'
down_revision: Union[str, Sequence[str], None] = 'cb085172f4a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PENDING', 'REJECTED', 'ACCEPTED', 'ACTIVE', 'DELETED', name='avatarmoderationstatusenum').create(op.get_bind())
    op.create_table('avatars',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('moderation_status', postgresql.ENUM('PENDING', 'REJECTED', 'ACCEPTED', 'ACTIVE', 'DELETED', name='avatarmoderationstatusenum', create_type=False), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('moderated_by_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('s3_key', sa.String(length=1024), nullable=False),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('current_timestamp(0)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('current_timestamp(0)'), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.ForeignKeyConstraint(['moderated_by_id'], ['users.id'], name=op.f('fk_avatars_moderated_by_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_avatars_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_avatars')),
    sa.UniqueConstraint('s3_key', name=op.f('uq_avatars_s3_key'))
    )
    op.add_column('users', sa.Column('current_avatar_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_users_current_avatar_id_avatars'), 'users', 'avatars', ['current_avatar_id'], ['id'])
    op.drop_column('users', 'photo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_users_current_avatar_id_avatars'), 'users', type_='foreignkey')
    op.drop_column('users', 'current_avatar_id')
    op.drop_table('avatars')
    sa.Enum('PENDING', 'REJECTED', 'ACCEPTED', 'ACTIVE', 'DELETED', name='avatarmoderationstatusenum').drop(op.get_bind())
    # ### end Alembic commands ###
