import type { OrgNode, Employee } from "../types/types";

export const mockEmployees: Employee[] = [
  {
    id: "e1",
    name: "Иванов Сергей",
    firstName: "Сергей",
    lastName: "Иванов",
    email: "sergey.ivanov@novatech.io",
    position: "Senior Backend Engineer",
    city: "Москва",
    location: "Москва",
    skills: ["C#", ".NET Core", "PostgreSQL"],
    photoUrl: "/placeholder.svg",
  },
  {
    id: "e2",
    name: "Смирнова Анна",
    firstName: "Анна",
    lastName: "Смирнова",
    email: "anna.smirnova@novatech.io",
    position: "Product Manager",
    city: "Екатеринбург",
    location: "Екатеринбург",
    skills: ["Agile", "Продуктовая аналитика"],
  },
  {
    id: "e3",
    name: "Кузнецов Алексей",
    firstName: "Алексей",
    lastName: "Кузнецов",
    email: "alexey.kuznetsov@novatech.io",
    position: "DevOps Engineer",
    city: "Москва",
    location: "Москва",
    skills: ["Docker", "Kubernetes", "CI/CD"],
  },
  {
    id: "e4",
    name: "Волков Дмитрий",
    firstName: "Дмитрий",
    lastName: "Волков",
    email: "dmitriy.volkov@novatech.io",
    position: "Full-Stack Engineer",
    city: "Москва",
    location: "Москва",
    skills: ["React", "Node.js"],
  },
  {
    id: "e5",
    name: "Лебедева Ольга",
    firstName: "Ольга",
    lastName: "Лебедева",
    email: "olga.lebedeva@novatech.io",
    position: "QA Automation Engineer",
    city: "Екатеринбург",
    location: "Екатеринбург",
    skills: ["Selenium", "Python", "TestRail"],
  },
  {
    id: "e6",
    name: "Морозов Евгений",
    firstName: "Евгений",
    lastName: "Морозов",
    email: "evgeniy.morozov@novatech.io",
    position: "Data Scientist",
    city: "Москва",
    location: "Москва",
    skills: ["Python", "Машинное обучение"],
  },
  {
    id: "e7",
    name: "Новикова Екатерина",
    firstName: "Екатерина",
    lastName: "Новикова",
    email: "ekaterina.novikova@novatech.io",
    position: "Frontend Engineer",
    city: "Екатеринбург",
    location: "Екатеринбург",
    skills: ["Vue.js", "JavaScript"],
  },
  {
    id: "e8",
    name: "Беляков Игорь",
    firstName: "Игорь",
    lastName: "Беляков",
    email: "igor.belyakov@novatech.io",
    position: "Security Engineer",
    city: "Екатеринбург",
    location: "Екатеринбург",
    skills: ["Network Security", "Linux"],
  },
  {
    id: "e9",
    name: "Соколова Наталья",
    firstName: "Наталья",
    lastName: "Соколова",
    email: "natalya.sokolova@novatech.io",
    position: "HR",
    city: "Екатеринбург",
    location: "Екатеринбург",
    skills: ["Recruitment", "Communication"],
  },
];

export const mockOrgTree: OrgNode[] = [
  {
    id: "c1",
    name: "UDV Group",
    type: "company",
    children: [
      {
        id: "le1",
        name: "UDV Digital Transforamtion",
        type: "legal_entity",
        children: [
          {
            id: "d1",
            name: "ТриниДата",
            type: "department",
            children: [
              {
                id: "t1",
                name: "Основное подразделение",
                type: "team",
                children: [
                  {
                    id: "e1",
                    name: "Иванов Сергей",
                    type: "employee",
                    employeeId: "e1",
                  },
                  {
                    id: "e2",
                    name: "Смирнова Анна",
                    type: "employee",
                    employeeId: "e2",
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
];
