import type { OrgNode, Employee } from "../types/types";

export const mockEmployees: Employee[] = [
  {
    id: "e1",
    name: "Иванов Сергей Петрович",
    firstName: "Сергей",
    lastName: "Иванов",
    middleName: "Петрович",
    email: "sergey.ivanov@novatech.io",
    position: "Senior Backend Engineer",
    city: "Москва",
    location: "Москва",
    skills: ["C#", ".NET Core", "PostgreSQL"],
    photoUrl: "/placeholder.svg",
    legalEntity: "ТриниДата",
    departmentFull: "UDV Digital Transforamtion / ТриниДата / Основное подразделение",
    hireDate: "12.05.2019",
    salary: 280000,
    employmentStatus: "Работает",
    contractNumber: "ТД-2019-067",
  },
  {
    id: "e2",
    name: "Смирнова Анна Викторовна",
    firstName: "Анна",
    lastName: "Смирнова",
    middleName: "Викторовна",
    email: "anna.smirnova@novatech.io",
    position: "Product Manager",
    city: "Екатеринбург",
    location: "Екатеринбург",
    skills: ["Agile", "Продуктовая аналитика"],
    legalEntity: "ТриниДата",
    departmentFull: "UDV Digital Transforamtion / ТриниДата / Основное подразделение",
    hireDate: "08.03.2020",
    salary: 240000,
    employmentStatus: "Работает",
    contractNumber: "ТД-2020-034",
  },
  {
    id: "e3",
    name: "Кузнецов Алексей Иванович",
    firstName: "Алексей",
    lastName: "Кузнецов",
    middleName: "Иванович",
    email: "alexey.kuznetsov@novatech.io",
    position: "DevOps Engineer",
    city: "Москва",
    location: "Москва",
    skills: ["Docker", "Kubernetes", "CI/CD"],
    legalEntity: "ТриниДата",
    departmentFull: "UDV Digital Transforamtion / ТриниДата / Основное подразделение",
    hireDate: "22.11.2019",
    salary: 260000,
    employmentStatus: "Работает",
    contractNumber: "ТД-2019-112",
  },
  {
    id: "e4",
    name: "Волков Дмитрий Сергеевич",
    firstName: "Дмитрий",
    lastName: "Волков",
    middleName: "Сергеевич",
    email: "dmitriy.volkov@novatech.io",
    position: "Full-Stack Engineer",
    city: "Москва",
    location: "Москва",
    skills: ["React", "Node.js"],
    dateOfBirth: "11.11.1985",
    phone: "+7 (903) 222-64-97",
    departmentFull: "UDV Digital Transforamtion / ВНЕ ОЧЕРЕДИ / Основное подразделение",
    legalEntity: "ВНЕ ОЧЕРЕДИ",
    workExperience: "6 лет",
    aboutMe: "Руковожу командой, внедряю новые технологии и провожу ревью кода.",
    hireDate: "15.03.2018",
    salary: 250000,
    employmentStatus: "Работает",
    contractNumber: "ТД-2018-045",
    group: "Направление аналитики и документации",
  },
  {
    id: "e5",
    name: "Лебедева Ольга Николаевна",
    firstName: "Ольга",
    lastName: "Лебедева",
    middleName: "Николаевна",
    email: "olga.lebedeva@novatech.io",
    position: "QA Automation Engineer",
    city: "Екатеринбург",
    location: "Екатеринбург",
    skills: ["Selenium", "Python", "TestRail"],
    dateOfBirth: "29.01.1993",
    phone: "+7 (922) 134-55-68",
    mattermost: "@olgalebedeva",
    telegram: "@olgalebedeva",
    departmentFull: "UDV Digital Transforamtion / ВНЕ ОЧЕРЕДИ / Основное подразделение",
    legalEntity: "ВНЕ ОЧЕРЕДИ",
    managerName: "Дмитрий Волков",
    workExperience: "2 года",
    aboutMe: "Специалист по автоматизации тестирования. Обеспечиваю стабильность релизов и качество продукта.",
    hireDate: "10.05.2022",
    salary: 180000,
    employmentStatus: "Работает",
    contractNumber: "ТД-2022-128",
  },
  {
    id: "e6",
    name: "Морозов Евгений Владимирович",
    firstName: "Евгений",
    lastName: "Морозов",
    middleName: "Владимирович",
    email: "evgeniy.morozov@novatech.io",
    position: "Data Scientist",
    city: "Москва",
    location: "Москва",
    skills: ["Python", "Машинное обучение", "Pandas"],
    dateOfBirth: "03.07.1988",
    phone: "+7 (905) 763-49-70",
    departmentFull: "UDV Digital Transforamtion / ВНЕ ОЧЕРЕДИ / Основное подразделение",
    legalEntity: "ВНЕ ОЧЕРЕДИ",
    managerName: "Дмитрий Волков",
    workExperience: "3 года",
    aboutMe: "Работаю над внедрением моделей машинного обучения в бизнес-процессы компании. Специалист по анализу данных и прогнозированию.",
    hireDate: "20.08.2021",
    salary: 220000,
    employmentStatus: "Работает",
    contractNumber: "ТД-2021-089",
  },
  {
    id: "e7",
    name: "Новикова Екатерина Романовна",
    firstName: "Екатерина",
    lastName: "Новикова",
    middleName: "Романовна",
    email: "ekaterina.novikova@novatech.io",
    position: "Frontend Engineer",
    city: "Екатеринбург",
    location: "Екатеринбург",
    skills: ["Vue.js", "JavaScript"],
    legalEntity: "ФТ-СОФТ",
    departmentFull: "UDV Digital Transforamtion / ФТ-СОФТ / Основное подразделение",
    hireDate: "15.06.2021",
    salary: 200000,
    employmentStatus: "Работает",
    contractNumber: "ТД-2021-078",
  },
  {
    id: "e8",
    name: "Беляков Игорь Михайлович",
    firstName: "Игорь",
    lastName: "Беляков",
    middleName: "Михайлович",
    email: "igor.belyakov@novatech.io",
    position: "Security Engineer",
    city: "Екатеринбург",
    location: "Екатеринбург",
    skills: ["Network Security", "Linux"],
    legalEntity: "ФТ-СОФТ",
    departmentFull: "UDV Digital Transforamtion / ФТ-СОФТ / Основное подразделение",
    hireDate: "17.10.2020",
    salary: 230000,
    employmentStatus: "Работает",
    contractNumber: "ТД-2020-145",
    group: "Направление аналитики и документации",
    description: "Защищаю инфраструктуру, провожу аудит систем и тренинги по безопасности.",
  },
  {
    id: "e9",
    name: "Соколова Наталья Павловна",
    firstName: "Наталья",
    lastName: "Соколова",
    middleName: "Павловна",
    email: "natalya.sokolova@novatech.io",
    position: "HR",
    city: "Екатеринбург",
    location: "Екатеринбург",
    skills: ["Recruitment", "Communication"],
    legalEntity: "ФТ-СОФТ",
    departmentFull: "UDV Digital Transforamtion / ФТ-СОФТ / Основное подразделение",
    hireDate: "05.09.2020",
    salary: 150000,
    employmentStatus: "Работает",
    contractNumber: "ТД-2020-098",
  },
];

export const mockOrgTree: OrgNode[] = [
  {
    id: "c1",
    name: "UDV Group",
    type: "company",
    children: [
      {
        id: "le1",
        name: "UDV Digital Transforamtion",
        type: "legal_entity",
        children: [
          {
            id: "d1",
            name: "ТриниДата",
            type: "department",
            children: [
              {
                id: "t1",
                name: "Основное подразделение",
                type: "team",
                children: [
                  {
                    id: "e1",
                    name: "Иванов Сергей",
                    type: "employee",
                    employeeId: "e1",
                  },
                  {
                    id: "e2",
                    name: "Смирнова Анна",
                    type: "employee",
                    employeeId: "e2",
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
];
